CREATE TABLE Auto (
ID INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
Knz TEXT,
Farbe INTEGER NOT NULL REFERENCES Farbe(id),
Modell INTEGER NOT NULL REFERENCES Modell(id),
Filliale INTEGER NOT NULL REFERENCES Filliale(id)
);