### Alle Artikel lesen
GET http://localhost:8080/myappdata/articles
Accept: application/json

### Neuen Artikel mit ID = 3 hinzufügen
POST http://localhost:8080/myappdata/articles
Content-Type:application/json

{
  "id": 3,
  "bezeichnung": "Java for Professionals",
  "beschreibung": "Java-Buch für krasse Profis",
  "preisEK": 7.49,
  "preisVK": 19.99
}

### Artikel mit ID = 3 ändern
PUT http://localhost:8080/myappdata/articles
Content-Type:application/json

{
  "id": 1,
  "bezeichnung": "Java for Dullies",
  "beschreibung": "Java-Buch für dumme Profis",
  "preisEK": 9.49,
  "preisVK": 50.99
}

### Artikel mit der ID = 3 löschen
DELETE http://localhost:8080/myappdata/articles/1
Accept: : application/json